In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.simplefilter("ignore")

In [2]:
df = pd.read_csv("preprocessd_data.csv")
df

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls,churn
0,0,-0.264643,-0.946659,0,0,-1.508785,0.722258,-0.944404,-1.403000,-0.415473,0
1,0,0.029654,1.235009,0,0,0.304821,-0.901748,-0.688523,-0.599124,0.347522,0
2,0,2.580235,0.658246,0,0,-2.266627,0.613991,-0.483818,-1.403000,2.636507,1
3,0,-1.441834,0.783629,0,1,0.638123,-0.252146,0.079121,-0.197185,1.110517,0
4,0,0.127754,2.288228,0,0,-0.333851,0.253101,-0.893228,1.008630,-0.415473,0
...,...,...,...,...,...,...,...,...,...,...,...
3401,1,-0.805656,0.479710,0,0,0.887802,0.552184,0.865765,-0.495634,-0.415473,1
3402,0,0.477826,0.674425,0,0,2.038061,-0.931071,0.567257,2.100185,0.235227,1
3403,0,-0.550521,0.426099,0,1,-0.410669,0.344847,-0.729485,-0.403904,1.873512,1
3404,0,0.004651,-0.444637,0,0,1.359751,-0.847121,-0.715010,-0.197185,-1.178468,1
3405,0,-0.057028,0.317748,0,0,2.844852,0.098115,-0.550251,0.606692,-1.178468,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3406 entries, 0 to 3405
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gender                  3406 non-null   int64
 1   age                     3406 non-null   float64
 2   no_of_days_subscribed   3406 non-null   float64
 3   multi_screen            3406 non-null   int64
 4   mail_subscribed         3406 non-null   int64
 5   weekly_mins_watched     3406 non-null   float64
 6   minimum_daily_mins      3406 non-null   float64
 7   weekly_max_night_mins   3406 non-null   float64
 8   videos_watched          3406 non-null   float64
 9   customer_support_calls  3406 non-null   float64
 10  churn                   3406 non-null   int64
dtypes: float64(7), int64(4)
memory usage: 292.8 KB

In [4]:
df.describe()

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls,churn
count,3406.000000,3406.000000,3406.000000,3406.000000,3406.000000,3406.000000,3406.000000,3406.000000,3406.000000,3406.000000,3406.000000
mean,0.465062,0.000389,0.003975,0.129477,0.204639,0.188265,0.060254,-0.006607,-0.043962,0.220325,0.500000
std,0.498851,1.008410,0.926548,0.335777,0.403497,1.096522,0.956151,0.967685,0.963218,1.178672,0.500073
min,0.000000,-2.030430,-2.476335,0.000000,0.000000,-3.350322,-3.680602,-2.991455,-1.804939,-1.178468,0.000000
25%,0.000000,-0.657040,-0.620663,0.000000,0.000000,-0.551626,-0.549131,-0.687775,-0.622393,-0.415473,0.000000
50%,0.000000,-0.166544,0.003156,0.000000,0.000000,0.132585,0.036567,-0.023231,-0.197185,-0.389751,0.500000
75%,1.000000,0.422051,0.572720,0.000000,0.000000,1.023672,0.722258,0.693505,0.546053,1.110517,1.000000
max,1.000000,4.247922,3.592214,1.000000,1.000000,3.181641,3.537201,3.814990,5.831892,5.688486,1.000000

In [5]:
df.corr()

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls,churn
gender,1.000000,-0.028800,0.040614,-0.042241,0.002702,-0.024297,0.023988,0.040532,0.060902,-0.030670,-0.150691
age,-0.028800,1.000000,0.025874,-0.071500,-0.028710,0.043043,0.012735,-0.021865,-0.035014,-0.031415,0.004910
no_of_days_subscribed,0.040614,0.025874,1.000000,0.010034,0.001408,-0.018797,-0.009303,-0.025902,-0.004052,0.009551,0.005361
multi_screen,-0.042241,-0.071500,0.010034,1.000000,0.001635,-0.018034,0.162120,0.084082,-0.033326,-0.082686,0.179276
mail_subscribed,0.002702,-0.028710,0.001408,0.001635,1.000000,-0.093507,0.020669,-0.003910,0.017830,0.003500,-0.235062
weekly_mins_watched,-0.024297,0.043043,-0.018797,-0.018034,-0.093507,1.000000,0.004018,0.047113,0.097088,-0.249796,0.231060
minimum_daily_mins,0.023988,0.012735,-0.009303,0.162120,0.020669,0.004018,1.000000,0.061842,0.062544,-0.019744,0.090789
weekly_max_night_mins,0.040532,-0.021865,-0.025902,0.084082,-0.003910,0.047113,0.061842,1.000000,-0.019293,-0.061330,-0.004311
videos_watched,0.060902,-0.035014,-0.004052,-0.033326,0.017830,0.097088,0.062544,-0.019293,1.000000,-0.051561,-0.054110
customer_support_calls,-0.030670,-0.031415,0.009551,-0.082686,0.003500,-0.249796,-0.019744,-0.061330,-0.051561,1.000000,0.256271
churn,-0.150691,0.004910,0.005361,0.179276,-0.235062,0.231060,0.090789,-0.004311,-0.054110,0.256271,1.000000

In [6]:
X = df.drop("churn",axis=1)
print(X)
print("="*100)

y = df["churn"]
print(y)
print("="*100)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=6)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

      gender       age  no_of_days_subscribed  multi_screen  mail_subscribed  \
0          0 -0.264643              -0.946659             0                0
1          0  0.029654               1.235009             0                0
2          0  2.580235               0.658246             0                0
3          0 -1.441834               0.783629             0                1
4          0  0.127754               2.288228             0                0
...      ...       ...                    ...           ...              ...
3401       1 -0.805656               0.479710             0                0
3402       0  0.477826               0.674425             0                0
3403       0 -0.550521               0.426099             0                1
3404       0  0.004651              -0.444637             0                0
3405       0 -0.057028               0.317748             0                0

      weekly_mins_watched  minimum_daily_mins  weekly_max_night_mins  \
0               -1.508785            0.722258              -0.944404
1                0.304821           -0.901748              -0.688523
2               -2.266627            0.613991              -0.483818
3                0.638123           -0.252146               0.079121
4               -0.333851            0.253101              -0.893228
...                   ...                 ...                    ...
3401             0.887802            0.552184               0.865765
3402             2.038061           -0.931071               0.567257
3403            -0.410669            0.344847              -0.729485
3404             1.359751           -0.847121              -0.715010
3405             2.844852            0.098115              -0.550251

      videos_watched  customer_support_calls
0          -1.403000               -0.415473
1          -0.599124                0.347522
2          -1.403000                2.636507
3          -0.197185                1.110517
4           1.008630               -0.415473
...              ...                     ...
3401       -0.495634               -0.415473
3402        2.100185                0.235227
3403       -0.403904                1.873512
3404       -0.197185               -1.178468
3405        0.606692               -1.178468

[3406 rows x 10 columns]
====================================================================================================
0       0
1       0
2       1
3       0
4       0
       ..
3401    1
3402    1
3403    1
3404    1
3405    1
Name: churn, Length: 3406, dtype: int64
====================================================================================================

DecisionTreeClassifier()

In [7]:
ypred_train = model.predict(X_train)
print(ypred_train)
ypred_test = model.predict(X_test)
print(ypred_test)

[1 0 1 ... 1 1 1]
[0 1 0 1 1 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 0
 1 1 1 1 1 0 1 1 0 1 1 1 0 0 1 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1
 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1
 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 0 0
 1 0 1 0 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 0 1 1 1 0 1
 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 0
 1 1 0 1 1 0 1 1 0 0 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0
 0 1 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0
 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 0 0 1 0 1 1 0 0
 1 1 1 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 1 1 0 1 1 1 1
 1 1 1 0 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 0
 1 0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1
 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1
 0 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 1 0 0 0 0 1 1
 0 1 0 1 1 0 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 1 0 1 0 1 1 1 1 1 1 0 0 1 0
 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 1 1 1 1
 0 1 0 1 1 0 0 1 0 0 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 1
 1 0 1 1 0 0 1 1 1 1 1 1 0 1 0 0]

In [8]:
train_accuracy = model.score(X_train,y_train)
print("train_accuracy",train_accuracy)
test_accuracy = model.score(X_test,y_test)
print("test_accuracy",test_accuracy)

from sklearn.model_selection import cross_val_score
scores = cross_val_score(model,X,y,cv=5)
print("cross_val_score",scores.mean())

train_accuracy 1.0
test_accuracy 0.9002932551319648
cross_val_score 0.8816928701538622

In [ ]:
from sklearn.tree import plot_tree 

plt.figure(figsize=(20,24),dpi=300)   # It will increses the Decision Tree size.

plot_tree(model,filled=True,feature_names=list(X_train.columns),
         #eature_names=["gender", "age", "no_of_days_subscribed", "multi_screen mail_subscribed","weekly_mins_watched","minimum_daily_mins","weekly_max_night_mins" ,"videos_watched" ,"customer_support_calls"],
          class_names=["0","1"])
plt.show()

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

estimator = DecisionTreeClassifier()
grid_param = {"criterion":["gini","entropy"],"max_depth":[2,3,4,5,6],"max_leaf_nodes":[1,2,3]}

dt_classifier = GridSearchCV(estimator,grid_param,cv=5,scoring="accuracy",verbose=True)
dt_classifier.fit(X_train,y_train)

dt_classifier.best_params_

In [ ]:
dt_classifier.best_estimator_

In [ ]:
dt_classifier.best_score_

In [ ]:
import time
start = time.time()
dt_classifier.fit(X_train,y_train)
end = time.time()
print("Total time taken to fit the model is:",(end-start))

In [ ]:
dt_classifier

In [ ]:
dir(dt_classifier)

In [ ]:
dt_classifier.best_estimator_.feature_importances_

In [ ]:
important_features = list(dt_classifier.best_estimator_.feature_importances_)
important_features

In [ ]:
feats = pd.DataFrame(important_features,index=X.columns,columns=["Importance Features"])
feats

In [ ]:
imp_feats = imp_df[imp_df["Importance"]>0]
imp_feats